export interface IAfkHomeStates {
    isSuccess: any;
    showExtraSpan: any;
    isError: any;
    isInGroup:any;
    error:any
    isLoader: any;
    isSuccessDialogVisible: any;
    successMessageDesciption: any;
    successMessageTitle: any;
    errorDesciption: any;
    errorTitle: any;
    isDialogVisible: any;
    allIdeaList: any;
    imageList: any;
    token: any;
    comment: any;
    commentList: any;
    isCommentShow: any;
    isCommentLoadMore: any;
    allCommentList: any;
    editID: any;
    ideaID: any;
    startnum: any;
    limit: any;
    filterName: any;
    isBookmarkModalOpen: any;
    replyComment: any;
    replyCommentList: any;
    allReplyCommentList: any;
    isReplyCommentShow: any;
    replyStage1Comment: any;
    replyStage1CommentList: any;
    reportIdeaId: any
    reportCommentId: any;
    stage1CommentReportDialog: any;
    stage2CommentReportDialog: any;
    reportRepliesId: any;
    editComment: any;
    isReplyShowtextBox: any;
    isReply2ShowtextBox: any;
    ReplyCommenteditID: any;
    editReplyComment: any;
    ideaReply2CommentId: any;
    CommentReplyId: any;
    automateTitle: any;
    automateOwner: any;
    automateComment: any;
    filterWithCase: any;
    bookMarkClass: any;
    bookMarkDesc: any;
    modalClass: any;
    modalTime: any;
    attachments: any;
    profileAttachments: any;
    uniqueIds: any;
    sK0y: any;
    isHMAC: any;
    Title: any;
    dropdownClass: any;
    designationList: any;
    //designationList
    lang: any;
    class: any;
    englishContent: any;
    arabicContent: any;
    addedtoyourbookmarks: any;
    recent: any;
    implemented: any;
    latestsubmissions: any;
    oldsubmissions: any;
    mostliked: any;
    mostcomments: any;
    onlyyouractivity:any;
    Recent:any;
    bookmarksremoved:any;
    searchText: any;
}
