export interface IAfkIdeainnerpageStates {
  isSuccess?: any;
  showExtraSpan: any;
  showexttraReplySpan: any;
  isLoader?: any;
  isDialogVisible?: any;
  isSuccessDialogVisible?: any;
  errorDesciption?: any;
  errorTitle?: any;
  successMessageDesciption?: any;
  successMessageTitle?: any;
  ideaTitle?: any;
  submitterEmailID?: any;
  userImage?: any;
  submitterUserName?: any;
  files?: any;
  ideaDesc?: any;
  enteredon?: any;
  status?: any;
  voteCnt?: any;
  commentCnt?: any;
  isShowCreateCampaign?: any;
  sharesCnt?: any;
  benefit?: any;
  ideapath?: any;
  imageList?: any;
  IdeaTrackingList?: any;
  commentList?: any;
  comment?: any;
  editID?: any;
  ideaID?: any;
  isReplyCommentShow?: any;
  replyComment?: any;
  replyCommentList?: any;
  englishContent?: any;
  arabicContent?: any;
  cntcomment?: any;
  cntvote?: any;
  cntshare?: any;
  reportIdeaId?: any;
  reportCommentId?: any;
  stage1CommentReportDialog?: any;
  stage2CommentReportDialog?: any;
  reportRepliesId?: any;
  editComment?: any;
  isReplyShowtextBox?: any;
  isReply2ShowtextBox?: any;
  ReplyCommenteditID?: any;
  editReplyComment?: any;
  ideaReply2CommentId?: any;
  CommentReplyId?: any;
  profileAttachments?: any;
  uniqueIds?: any;
  sK0y?: any;
  isHMAC?: any;
  token?: any;
  submitterEmailId?: any;
  lang?: any;
  class?: any;
  modalClass?: any;
  bookMarkDesc: any;
  userbookmark: any;
  bookMarkClass:any;
  addedtoyourbookmarks: any;
  isBookmarkModalOpen:any;
  bookmarksremoved: any;
  reportthiscomment?: any;
  designationList?: any;
  approverroleList?: any;
  isInGroup: boolean | null;
  error: string | null;
  division:any;
  ideatype:any;
  value_chain:any;
  innovationenablers:any;
  showFullDesc: any;
}
